version: "3.4"

services:
  server:
    image: stardustdl/loment:latest
    ports:
      - "4000:80"
    environment:
      - LOMENT_DBORIGIN=root:123456@(db:3306)
      - LOMENT_DBNAME=loment_db
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    security_opt:
      - seccomp:unconfined
    volumes:
      - data:/var/opt/mssql
volumes:
  data: